import { Manrope } from "next/font/google";
import "./globals.css";

const manrope = Manrope({
  variable: "--manrope",
  subsets: ["latin"],
});

export const metadata = {
  title: "Find food anywhere!",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link
        href="https://api.mapbox.com/mapbox-gl-js/v1.10.1/mapbox-gl.css"
        rel="stylesheet"
      />
      </head>
      <body
        className={`${manrope.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
